"""
Django settings for hospital_api project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

from django.utils import timezone

from .config import get_config

config = get_config()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.django.secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config.django.debug

ALLOWED_HOSTS = config.django.allowed_hosts

CSRF_TRUSTED_ORIGINS = config.django.csrf_trusted_origins

CORS_ALLOWED_ORIGINS = config.django.cors_allowed_origins

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'phonenumber_field',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_rest_passwordreset',
    'corsheaders',
    'storages',

    'apps.accounts.apps.AccountsConfig',
    'apps.doctors.apps.DoctorsConfig',
    'apps.patients.apps.PatientsConfig',
    'apps.managers.apps.ManagersConfig',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hospital_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hospital_api.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
    'DEFAULT_VERSION': 'v1',
    'ALLOWED_VERSIONS': ('v1',),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timezone.timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME': timezone.timedelta(days=60),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACK_LIST_AFTER-ROTATION': True,
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config.smtp.host
EMAIL_HOST_USER = config.smtp.host_user
EMAIL_HOST_PASSWORD = config.smtp.password
EMAIL_PORT = config.smtp.port
EMAIL_USE_TLS = True

FRONTEND_DOMAIN = config.frontend.domain
FRONTEND_PASSWORD_RESET_URL = f'{FRONTEND_DOMAIN}reset_password/confirm/'

DEFAULT_FILE_STORAGE = 'hospital_api.s3_storage.MediaStorage'
SELECTEL_CUSTOM_URL = config.s3.selectel_url
AWS_S3_ENDPOINT_URL = config.s3.endpoint_url
AWS_S3_ACCESS_KEY_ID = config.s3.access_key_id
AWS_S3_SECRET_ACCESS_KEY = config.s3.secret_access_key
AWS_STORAGE_BUCKET_NAME = config.s3.bucket_name
AWS_S3_USE_SSL = True
AWS_S3_VERIFY = False
