# Generated by Django 5.0.6 on 2024-06-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
