# Generated by Django 5.0.6 on 2024-06-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_direction_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='slug',
            field=models.SlugField(default=None, null=True, unique=True),
        ),
    ]
